#!/bin/bash

# k-Winners-Take-All Ensemble Neural Network
# Copyright (C) 2021  Abien Fred Agarap
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

python -m modules.moe_inspector 1234-seed-moe-3-dnn-kmnist-0.1-lr-opt-sgd-100-bsize.pth 1001
python -m modules.ensemble_inspector 73-seed-ensemble-3-dnn-kmnist-0.1-lr-opt-sgd-100-bsize.pth 1001
python -m modules.kwta_inspector 73-seed-kwta_enn-3-dnn-kmnist-cd-0-s-0.75-0.1-lr-opt-sgd-100-bsize.pth 1001
