#!/bin/bash

# k-Winners-Take-All Ensemble Neural Network
# Copyright (C) 2021  Abien Fred Agarap
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

python -m modules.kwta_inspector 31415-seed-kwta_enn-3-dnn-mnist-cd-0-s-0.75-0.1-lr-opt-sgd-100-bsize.pth 39

python -m modules.ensemble_inspector 86400-seed-ensemble-3-dnn-mnist-0.1-lr-opt-sgd-100-bsize.pth 39

python -m modules.moe_inspector 1234-seed-moe-3-dnn-mnist-0.1-lr-opt-sgd-100-bsize.pth 39
